services:
  - type: web
    name: sgbuildex-validator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn sgbuildex_api_validator:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
